In [2]:
import numpy as np

a = np.arange(20)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
type(a)

numpy.ndarray

In [5]:
a = a.reshape(5,4)

In [6]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
a.mean()

9.5

In [16]:
a.mean(axis = 0) # average by column

array([ 8.,  9., 10., 11.])

In [17]:
a.mean(axis = 1) # average by row

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [20]:
a[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
a[:4, 2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [23]:
a[:4, 2:4].mean()

8.5

In [24]:
a[:4, 2:4].mean(1)

array([ 2.5,  6.5, 10.5, 14.5])

In [25]:
a[:4, 2:4].mean(0)

array([8., 9.])

In [26]:
pwd

'/Users/wzhang/GeneralAssembly/DAT-06-24/class material/Unit 2/Lesson 5'

In [27]:
import pandas as pd

In [31]:
df = pd.read_csv('../data/titanic.csv') # go up one level

In [34]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [36]:
df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [40]:
df.shape

(891, 12)

In [41]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [42]:
df.mean()

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [43]:
np.mean(df)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [47]:
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [67]:
df['Age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [68]:
df.Age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [50]:
df['Age'].values

array([22.  , 38.  , 26.  , 35.  , 35.  ,   nan, 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  ,   nan,
       31.  ,   nan, 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  ,   nan,
       19.  ,   nan,   nan, 40.  ,   nan,   nan, 66.  , 28.  , 42.  ,
         nan, 21.  , 18.  , 14.  , 40.  , 27.  ,   nan,  3.  , 19.  ,
         nan,   nan,   nan,   nan, 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  ,   nan, 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  ,   nan,   nan, 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  ,   nan,   nan,  0.83, 30.  , 22.  ,
       29.  ,   nan, 28.  , 17.  , 33.  , 16.  ,   nan, 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  ,   nan, 71.  , 23.  , 34.  ,
       34.  , 28.  ,   nan, 21.  , 33.  , 37.  , 28.  , 21.  ,   nan,
       38.  ,   nan, 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  ,   nan, 32.5 , 32.5 , 54.  , 12.  ,
         nan, 24.  ,

In [53]:
df['Age'][:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [54]:
df['Age'][:10].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [55]:
df['Age'][:10].mean()

28.11111111111111

In [59]:
df[['Name','Age','Fare']].head()

Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [60]:
df[['Name','Age','Fare']].sum()

Name    Braund, Mr. Owen HarrisCumings, Mrs. John Brad...
Age                                               21205.2
Fare                                              28693.9
dtype: object

In [58]:
df['Age'].nsmallest(5)

803    0.42
755    0.67
469    0.75
644    0.75
78     0.83
Name: Age, dtype: float64

In [61]:
df.iloc[2:7,[2,6,9]]

Pclass  SibSp     Fare
2       3      0   7.9250
3       1      1  53.1000
4       3      0   8.0500
5       3      0   8.4583
6       1      0  51.8625

In [65]:
df.iloc[2:7, :6]

PassengerId  Survived  Pclass  \
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   

                                           Name     Sex   Age  
2                        Heikkinen, Miss. Laina  female  26.0  
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  
4                      Allen, Mr. William Henry    male  35.0  
5                              Moran, Mr. James    male   NaN  
6                       McCarthy, Mr. Timothy J    male  54.0

In [66]:
df.iloc[2:7, ::2]

PassengerId  Pclass     Sex  SibSp            Ticket Cabin
2            3       3  female      0  STON/O2. 3101282   NaN
3            4       1  female      1            113803  C123
4            5       3    male      0            373450   NaN
5            6       3    male      0            330877   NaN
6            7       1    male      0             17463   E46

In [69]:
df.Age > 25

0      False
1       True
2       True
3       True
4       True
5      False
6       True
7      False
8       True
9      False
10     False
11      True
12     False
13      True
14     False
15      True
16     False
17     False
18      True
19     False
20      True
21      True
22     False
23      True
24     False
25      True
26     False
27     False
28     False
29     False
       ...  
861    False
862     True
863    False
864    False
865     True
866     True
867     True
868    False
869    False
870     True
871     True
872     True
873     True
874     True
875    False
876    False
877    False
878    False
879     True
880    False
881     True
882    False
883     True
884    False
885     True
886     True
887    False
888    False
889     True
890     True
Name: Age, Length: 891, dtype: bool

In [70]:
df[df.Age > 25]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
8              9         1       3   
11            12         1       1   
13            14         0       3   
15            16         1       2   
18            19         0       3   
20            21         0       2   
21            22         1       2   
23            24         1       1   
25            26         1       3   
30            31         0       1   
33            34         0       2   
34            35         0       1   
35            36         0       1   
40            41         0       3   
41            42         0       2   
52            53         1       1   
53            54         1       2   
54            55         0       1   
57            58         0       3   
61            62         1       1   
62            63         0       1   
66            67         1       2   
69            70         0       3   
70            71         0       2   
73            74         0       3   
..           ...       ...     ...   
823          824         1       3   
829          830         1       1   
835          836         1       1   
838          839         1       3   
842          843         1       1   
843          844         0       3   
845          846         0       3   
847          848         0       3   
848          849         0       2   
851          852         0       3   
854          855         0       2   
856          857         1       1   
857          858         1       1   
860          861         0       3   
862          863         1       1   
865          866         1       2   
866          867         1       2   
867          868         0       1   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
879          880         1       1   
881          882         0       3   
883          884         0       2   
885          886         0       3   
886          887         0       2   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
20                                Fynney, Mr. Joseph J    male  35.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0      1   
30                            Uruchurtu, Don. Manuel E    male  40.0      0   
33                               Wheadon, Mr. Edward H    male  66.0      0   
34                             Meyer, Mr. Edgar Joseph    male  28.0      1   
35                      Holverson, Mr. Alexander Oskar    male  42.0      1   
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.0      1   
41   Turpin, Mrs. William John Robert (Dorothy Ann ...  female  27.0

In [71]:
df[df.Age > 25].iloc[:, :5]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
6              7         0       1   
8              9         1       3   
11            12         1       1   
13            14         0       3   
15            16         1       2   
18            19         0       3   
20            21         0       2   
21            22         1       2   
23            24         1       1   
25            26         1       3   
30            31         0       1   
33            34         0       2   
34            35         0       1   
35            36         0       1   
40            41         0       3   
41            42         0       2   
52            53         1       1   
53            54         1       2   
54            55         0       1   
57            58         0       3   
61            62         1       1   
62            63         0       1   
66            67         1       2   
69            70         0       3   
70            71         0       2   
73            74         0       3   
..           ...       ...     ...   
823          824         1       3   
829          830         1       1   
835          836         1       1   
838          839         1       3   
842          843         1       1   
843          844         0       3   
845          846         0       3   
847          848         0       3   
848          849         0       2   
851          852         0       3   
854          855         0       2   
856          857         1       1   
857          858         1       1   
860          861         0       3   
862          863         1       1   
865          866         1       2   
866          867         1       2   
867          868         0       1   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
879          880         1       1   
881          882         0       3   
883          884         0       2   
885          886         0       3   
886          887         0       2   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  
2                               Heikkinen, Miss. Laina  female  
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  
4                             Allen, Mr. William Henry    male  
6                              McCarthy, Mr. Timothy J    male  
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  
11                            Bonnell, Miss. Elizabeth  female  
13                         Andersson, Mr. Anders Johan    male  
15                    Hewlett, Mrs. (Mary D Kingcome)   female  
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  
20                                Fynney, Mr. Joseph J    male  
21                               Beesley, Mr. Lawrence    male  
23                        Sloper, Mr. William Thompson    male  
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  
30                            Uruchurtu, Don. Manuel E    male  
33                               Wheadon, Mr. Edward H    male  
34                             Meyer, Mr. Edgar Joseph    male  
35                      Holverson, Mr. Alexander Oskar    male  
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  
41   Turpin, Mrs. William John Robert (Dorothy Ann ...  female  
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  
53   Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  
54                      Ostby, Mr. Engelhart Cornelius    male  
57                                 Novel, Mr. Mansouer    male  
61                     

In [73]:
df[df.Age>25]['Survived'][:100]

1      1
2      1
3      1
4      0
6      0
8      1
11     1
13     0
15     1
18     0
20     0
21     1
23     1
25     1
30     0
33     0
34     0
35     0
40     0
41     0
52     1
53     1
54     0
57     0
61     1
62     0
66     1
69     0
70     0
73     0
      ..
169    0
170    0
174    0
177    0
178    0
179    0
187    1
188    0
189    0
190    1
194    1
195    1
197    0
200    0
202    0
203    0
206    0
207    1
209    1
211    1
213    0
215    1
216    1
217    0
218    1
219    0
221    0
222    0
224    1
230    1
Name: Survived, Length: 100, dtype: int64

In [79]:
df[(df.Survived == 1)|(df.Age > 25)].shape

(589, 12)

In [80]:
df[(df.Survived == 1)&(df.Age > 25)].shape

(166, 12)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [82]:
df['new_column'] = df['Age'] ** 2

In [83]:
columns = df.columns.tolist()

In [84]:
columns

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked',
 'new_column']

In [85]:
columns_v2 = ['PassengerId', 'Name',
 'Survived',
 'Pclass',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked',
 'new_column']

In [86]:
df_v2 = df[columns_v2]

In [87]:
df_v2.columns

Index(['PassengerId', 'Name', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'new_column'],
      dtype='object')